#+STARTUP: content indent hideblocks
#+TITLE: Data assimilation issues
#+OPTIONS: ^:{} toc:nil
#+PROPERTY: header-args:python :session *Python* :tangle yes

#+NAME: session_init
#+BEGIN_SRC python :session :results silent :exports none
import matplotlib as mpl
mpl.use("Agg")
mpl.rcParams['mathtext.fontset']='stix'
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg2 as pg
from mpl_toolkits.basemap import Basemap
plt.style.use('ggplot')
conn = pg.connect("host=net82.ceos.umanitoba.ca port=5433 dbname=gases")
#+END_SRC

* Navigation

- No processed data from POSMV or CNAV are available at time of loading, so
  data will have to be merged manually via a view on the database.
  Requested and received complete merged product from U Laval.
- Somehow no data were saved to the portable drive between mid-June to
  mid-July.

Missing data due to turning off of most systems at this time, so no longer
an issue.

* Meteorology

Doubts on which wind direction from AAVOS should be used for loading have
crept in.  See email to Colline Gombault on 2017-11-03.  Resolved by
establishing that it was a mistake on the header of their processed files,
whereby apparent wind was labelled "true" wind.  It is indeed apparent
wind, as indicated in the raw data format description.

* Radiation

All well.

* Flux

** Offsets
:PROPERTIES:
:EXPORT_DATE:
:EXPORT_FILE_NAME: instrument_offsets
:EXPORT_OPTIONS: toc:nil
:EXPORT_AUTHOR:
:END:

Brian B emailed some estimates of offsets between flux instruments

[[gnus:nnimap+Exchange:INBOX#BD333764-4EB5-4D3B-A84E-0C79593896C1@ucalgary.ca][Email from Brian Butterworth: Re: mounting measurements]]

*** Sonic anemometers

Angular offset from straight forward:

| Anemometer          | Forward offset (degrees from forward) |
|---------------------+---------------------------------------|
| CSAT3               | 0                                     |
| Gill WindMaster Pro | 0                                     |

It was not clear what the angular offset of the Gill WindMaster Pro spar
is.  In photos, it seems to be zero, which was corroborated by measuring
mounting arm and plate in relation to mounting position of anemometer.

*** Relative to CSAT3

| Instrument | x (cm) | y (cm) | z (cm) |
|------------+--------+--------+--------|
| LGR        |    -30 |      3 |    -20 |
| LI-7200    |    -23 |      3 |    -18 |
| LI-7500A   |    -40 |     31 |     30 |
| Motion Pak | -64.77 |      0 |  -13.5 |

*** Relative to Gill WindMaster Pro

There seems to be a mistake in BB's email regarding the offsets of Gill
sonic anemometer relative to CSAT3.  The correct interpretation seems to
be: x=25 cm, y=-43 cm, z=-139 cm.  Therefore, using these, we derive:

| Instrument | x (cm) | y (cm) | z (cm) |
|------------+--------+--------+--------|
| LGR        |    -55 |    -46 |    119 |
| LI-7200    |    -48 |    -46 |    121 |
| LI-7500A   |    -65 |    -74 |    169 |
| Motion Pak | -89.77 |    -43 | -125.5 |

** Heights

Actual heights of instruments above deck were not measured, but can be
derived from photos and comparing with 2016, as well as taking into account
the offsets determined above.  This leads to the following heights above
the water line:

| Instrument                      | height (m) |
|---------------------------------+------------|
| Motion Pak                      |     16.725 |
| WindMaster Pro measuring volume |      15.47 |
| LI-7200 inlet                   |      16.68 |
| LI-7500A measuring volume       |      17.16 |
| LGR inlet                       |      16.66 |
| CSAT3 measuring volume          |      16.86 |
| RM Young wind monitor           |      17.62 |
| HMP155A temperature/RH sensor   |      16.13 |
| SI-111 IR sensor                |        8.4 |
| BPA4116 barometer               |       9.97 |

** Tower down periods

Looking at Motion Pak data, it seems as if there was only one tower-down
period: 2017-07-10 21:35 - 2017-07-11 00:10

** Units

Although units in data output from LGR are all ppm (umol/mol), it is not
clear at all whether CH4, CO2, and H2O correspond to dry or wet air moles.
Waiting for Brian/LGR to clarify this.

Resolved by LGR, confirming analog outputs correspond to dry mole ratios.

* Underway pCO2

All well.
